# FOR THIS PROJECT I WILL USE THE INSTRUCTIONS PRESENTS ON HAND-ON-IN MACHINE LEARNING WITH SCIKIT LEARN.... BY AURÉLION GERON

**THIS IS THE 2 CHAPTER, AND MY FIRST MACHINE LEARNING PROJECT, ILL DO THAT WITH BOOKS LEARNING, AND MY KNOWLEDGE ABOUT THE THEME**

### 1. ANALYZE THE SITUAION
**QUESTIONS**
- What's the real problem? -> The prices of houses in California it's calculate manually fro researches, and costs it money and time, so we gonna need to do a model to improve that

- What's the final objective? -> We need to predict the 'price values' of the houses, so we gonna use PREDICT objective.

- How the model will be used? -> The model will be used like an app (in this case a terminal it's ok), and we gonna use a old dataset, without new data, so it's once a time train

- The model have restrictions? -> No.

- In the future, the problem will be changed? -> No.

- In the futur, new data will come? No.

- Define the system os ml project -> (A: Supevised, B: batch (offline), C: modules, D: to define yet, E: to define yet, F: to define yet)

### 2. GET THE DATA
**WHERE'S THE DATA COME?**
- From a .csv file

In [106]:
import pandas as pd

# create a variable to get the dataset from .csv
dataset = pd.read_csv('../../datasets/housing.csv')
dataset.head() # verify if we realy get the dataset


# IN THIS CASE MEDIAN_HOUSE_VALUE IT'S THE TARGET (Y)
# AND ALL OTHERS IT'S THE FEATURES(X)

   longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

### 3. EDA AND PREPROCESSING

**EDA PART, WHICH STRATEGIES WILL BE USED?**
- All presentes on workflow

**EDA CHOOSE TO PREPROCESSING**
- CATEGORIAL FEATURE
- NULL VALUES
- SCALE AWARENESS

In [107]:
# CONSTANT FEATURES - ALL OK
# verify if have a feature with the same value in all the samples


dataset.nunique() # -> this function return all te the differnet values in a featuure, if 
# so in this case we don't have a constant feature

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [108]:
# REDUNDANT FEATURES - ALL OK
# verify if have a more than 1 feature with the same information but in a different way
# 90% if the cases we can see with eyes, doesn't need a function

dataset.head() # -> return the first 5 samples of the dataset

   longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [109]:
# CATEGORICAL FEATURES - 1 FEATURE
# verify if we have features with object, class or string data

dataset.info() # -> return all the values with their type
# in this case we have a feature 'OCEAN_PROXIMITY' that a object feature, and if we want to use, we need to change it laterw

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [110]:
# TIME FEATURES - ALL OK
# verify if the dataset have any information about time

dataset.head()

   longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [111]:
# CARDINALITY - ALL OK
# verify if we have differents values from a same feature, so can harm the model, and sometimes it's better remove it
# first we need to compare the total samples that we gonna train, with the cardinality
dataset.shape # 20640,10 samples
dataset.nunique()
# in this case how we only have 1 categorial feature and 5 cardinality in this feature, we dont change nothing

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [112]:
# NULL VALUES - 1 FEATURE
# We need to verify if some feature have a null value to delete it the samples

dataset.isnull().sum() # -> in this case ['TOTAL_BEDROOMNS'] have 20433 values, so in this feature we have some null values

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [113]:
# HIGH CORRELATION - CAN ADD SOME FEATURES TO IMPROVE
# We gonna verify the correlation between the features



# corr = dataset.corr() now we can't do that, because the feature ['ocean_proximity'] as a object feature, so we need to transform that in numeric feature to after see the correlation
# We gonna create 4 features with binary data
dataset_eda = dataset.copy()
dataset_enco = pd.get_dummies(dataset_eda, columns=["ocean_proximity"], drop_first=True)
dataset_corr = dataset_enco.corr()
dataset_corr['median_house_value'].sort_values(ascending= False)


# median_income FEATURE MAIS IMPACTANTE na correlação

median_house_value            1.000000
median_income                 0.688075
ocean_proximity_NEAR BAY      0.160284
ocean_proximity_NEAR OCEAN    0.141862
total_rooms                   0.134153
housing_median_age            0.105623
households                    0.065843
total_bedrooms                0.049686
ocean_proximity_ISLAND        0.023416
population                   -0.024650
longitude                    -0.045967
latitude                     -0.144160
ocean_proximity_INLAND       -0.484859
Name: median_house_value, dtype: float64

In [114]:
# SCALE AWARENESS - 1 feature
# Verify if a feature or more have different values from the others

print(f"The min values of the dataset: \n{dataset.min()}\n\n\n\n")
print(f"The max values of the dataset: \n{dataset.max()}\n\n\n\n")
print(f"The describe of dataset:")
dataset.describe()


# WE CAN SEE SOME FEATURES HAVE A HIGH SCALE AWARENESS LIKE
# MEDIAN_INCOME HAS A BIG VALUES FROM THE OTHERS

The min values of the dataset:
longitude               -124.35
latitude                  32.54
housing_median_age          1.0
total_rooms                 2.0
total_bedrooms              1.0
population                  3.0
households                  1.0
median_income            0.4999
median_house_value      14999.0
ocean_proximity       <1H OCEAN
dtype: object




The max values of the dataset:
longitude                -114.31
latitude                   41.95
housing_median_age          52.0
total_rooms              39320.0
total_bedrooms            6445.0
population               35682.0
households                6082.0
median_income            15.0001
median_house_value      500001.0
ocean_proximity       NEAR OCEAN
dtype: object




The describe of dataset:

          longitude      latitude  ...  median_income  median_house_value
count  20640.000000  20640.000000  ...   20640.000000        20640.000000
mean    -119.569704     35.631861  ...       3.870671       206855.816909
std        2.003532      2.135952  ...       1.899822       115395.615874
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.800000     33.930000  ...       2.563400       119600.000000
50%     -118.490000     34.260000  ...       3.534800       179700.000000
75%     -118.010000     37.710000  ...       4.743250       264725.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [115]:
# FEATURE ENGINEERING
# We gonna try to create new feature to represante better the reality

**PREPROCESSING, WHICH STRATEGIES WILL BE USED?**
- All presents on workflow

In [116]:
#############################
# WHAT WE NEED TO DO IN PREPROCESSING?
# - CATEGORIAL FEATURE
# - NULL VALUES
# - SCALE AWARENESS 
##############################################

In [117]:
############ CATEGORICAL FEATURE ###########################
# 1. We are going to use categorical encoding -> ONE-HOT ENCODING

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# HOW IT WORKS:
# We take the categorical feature and its cardinality
# and transform each category into a binary feature

# STEP 1: Identify the categorical feature
categorical_feature = ['ocean_proximity']

# STEP 2: Cardinality already identified in EDA (5 categories)

# STEP 3: Create the encoder
encoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

# STEP 4: Fit the encoder (learn categories)
encoder.fit(dataset[categorical_feature])

# STEP 5: Transform the feature
dataset_encoded = encoder.transform(dataset[categorical_feature])

# STEP 6: Get feature names
encoded_feature_names = encoder.get_feature_names_out(categorical_feature)

# STEP 7: Convert to DataFrame
dataset_encoded_df = pd.DataFrame(
    dataset_encoded,
    columns=encoded_feature_names,
    index=dataset.index
)

# STEP 8: Drop original categorical feature
dataset = dataset.drop(columns=categorical_feature)

# STEP 9: Concatenate encoded features
dataset = pd.concat([dataset, dataset_encoded_df], axis=1)

In [118]:
dataset.head()

   longitude  latitude  ...  ocean_proximity_NEAR BAY  ocean_proximity_NEAR OCEAN
0    -122.23     37.88  ...                       1.0                         0.0
1    -122.22     37.86  ...                       1.0                         0.0
2    -122.24     37.85  ...                       1.0                         0.0
3    -122.25     37.85  ...                       1.0                         0.0
4    -122.25     37.85  ...                       1.0                         0.0

[5 rows x 14 columns]

In [119]:
##################### NULL VALUES ################################
# 1. We have only a feature with null values, and how we see at EDA, it's 207, a few compare to the 20640, so we are gonna remove these samples

# STEP 1: Remove with pandas functions dropna
dataset = dataset.dropna()
# STEP 2: Check 
print(dataset.isnull().sum())

longitude                     0
latitude                      0
housing_median_age            0
total_rooms                   0
total_bedrooms                0
population                    0
households                    0
median_income                 0
median_house_value            0
ocean_proximity_<1H OCEAN     0
ocean_proximity_INLAND        0
ocean_proximity_ISLAND        0
ocean_proximity_NEAR BAY      0
ocean_proximity_NEAR OCEAN    0
dtype: int64

In [120]:
#################### SCALE AWARENESS ###############
# To this after the split!

### 4. PREPARE THE DATA FOR ML
**TYPE OF SETs?**
- Train and tett 
**STRATEGIES TO SPLIT THE SETs**
- HOLDOUT

In [121]:
from sklearn.model_selection import train_test_split


# CREATE X and Y
X = dataset.drop(columns=['median_house_value'])
y = dataset['median_house_value']


# SPLIT THE DATA FOR TEST AND TRAIN
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### 5. GET THE MODEL
**LINEAR REGRESSION**

In [122]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import  r2_score

# GET THE MODEL
model = LinearRegression()

# TRAIN THE MODEL
model.fit(X_train, y_train)

# CHECK THE ACCURACY
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(f'{r2 * 100:.2f}% of accuracy')

65.39% of accuracy