# FOR THIS PROJECT I WILL USE THE INSTRUCTIONS PRESENTS ON HAND-ON-IN MACHINE LEARNING WITH SCIKIT LEARN.... BY AURÉLION GERON

**THIS IS THE 2 CHAPTER, AND MY FIRST MACHINE LEARNING PROJECT, ILL DO THAT WITH BOOKS LEARNING, AND MY KNOWLEDGE ABOUT THE THEME**

### 1. ANALYZE THE SITUAION
**QUESTIONS**
- What's the real problem? -> The prices of houses in California it's calculate manually fro researches, and costs it money and time, so we gonna need to do a model to improve that

- What's the final objective? -> We need to predict the 'price values' of the houses, so we gonna use PREDICT objective.

- How the model will be used? -> The model will be used like an app (in this case a terminal it's ok), and we gonna use a old dataset, without new data, so it's once a time train

- The model have restrictions? -> No.

- In the future, the problem will be changed? -> No.

- In the futur, new data will come? No.

- Define the system os ml project -> (A: Supevised, B: batch (offline), C: modules, D: to define yet, E: to define yet, F: to define yet)

### 2. GET THE DATA
**WHERE'S THE DATA COME?**
- From a .csv file

In [ ]:
import pandas as pd

# create a variable to get the dataset from .csv
dataset = pd.read_csv('../../datasets/housing.csv')
dataset.head() # verify if we realy get the dataset


# IN THIS CASE MEDIAN_HOUSE_VALUE IT'S THE TARGET (Y)
# AND ALL OTHERS IT'S THE FEATURES(X)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

### 3. EDA AND PREPROCESSING

**EDA PART, WHICH STRATEGIES WILL BE USED?**
- All presentes on workflow

**EDA CHOOSE**
- CATEGORIAL FEATURE

In [10]:
# CONSTANT FEATURES - ALL OK
# verify if have a feature with the same value in all the samples


dataset.nunique() # -> this function return all te the differnet values in a featuure, if 
# so in this case we don't have a constant feature

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [11]:
# REDUNDANT FEATURES - ALL OK
# verify if have a more than 1 feature with the same information but in a different way
# 90% if the cases we can see with eyes, doesn't need a function

dataset.head() # -> return the first 5 samples of the dataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [ ]:
# CATEGORICAL FEATURES - 1 FEATURE
# verify if we have features with object, class or string data

dataset.info() # -> return all the values with their type
# in this case we have a feature 'OCEAN_PROXIMITY' that a object feature, and if we want to use, we need to change it later

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [17]:
# TIME FEATURES - ALL OK
# verify if the dataset have any information about time

dataset.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [24]:
# CARDINALITY
# verify if we have differents values from a same feature, so can harm the model, and sometimes it's better remove it
# first we need to compare the total samples that we gonna train, with the cardinality
dataset.shape # 20640 samples

(20640, 10)

In [26]:
dataset.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

**PREPROCESSING, WHICH STRATEGIES WILL BE USED?**
- All presents on workflow

### 4. PREPARE THE DATA FOR ML
**TYPE OF SETs?**
- Train and tett 
**STRATEGIES TO SPLIT THE SETs**
- TO DEFINE YET